const omiglproBlockedWords = [
    'admin',
    'anonymous',
    'bot',
    'fuck',
    'nazi',
    'scam',
    'sex',
    'spam',
    'swastika',
    'xenophobe',
    'lavda',
    
    // English profanity
    'fucking',
    'fucker',
    'motherfucker',
    'shit',
    'bullshit',
    'bitch',
    'bastard',
    'asshole',
    'dumbass',
    'jackass',
    'dick',
    'cock',
    'pussy',
    'cunt',
    'whore',
    'slut',
    'hoe',
    'wanker',
    'prick',
    'douche',
    'douchebag',
     // Common sexual / explicit terms
    'porn',
    'porno',
    'pornography',
    'xxx',
    'nude',
    'nudes',
    'naked',
    'boobs',
    'tits',
    'tit',
    'vagina',
    'penis',
    'anus',
    'anal',
    'orgasm',
    'masturbate',
    'masturbation',
    'cum',
    'semen',
    'erection',
    'horny',
    'blowjob',
    'handjob',

    // Common Indian / Hindi profanity
    'bc',
    'mc',
    'bhenchod',
    'bhenchod',
    'behenchod',
    'madarchod',
    'madharchod',
    'chutiya',
    'chutiye',
    'chut',
    'chod',
    'chodu',
    'chodna',
    'chodai',
    'randi',
    'rand',
    'harami',
    'haraami',
    'kamina',
    'kamine',
    'kaminey',
    'kutte',
    'kutta',
    'gandu',
    'gaand',
    'gand',
    'gandfat',
    'lodu',
    'lauda',
    'lavda',
    'lund',
    'lulli',
    'jhant',
    'jhantu',
    'bhosdika',
    'bhosdi',
    'bhosda',
    'bhosdiwala',
    'bakchod',
    'bakchodi',
    'chinal',
    'chinala',
    'suar',
    'ullu',
    'nalayak',
 // Hinglish / Roman Hindi variants
    'teri maa',
    'teri ma',
    'teri behen',
    'teri bhen',
    'maa chuda',
    'ma chuda',
    'behen ki',
    'bhen ki',
    'maa ki',
    'ma ki',
    'gaand mara',
    'gand mara',
    'lund le',
    'chut le',
    // Sexual/body-part variants commonly used abusively
    'ass',
    'arse',
    'butt',
    'breast',
    'breasts',
    'boob',
    'boobs',
    'dickhead',
    'balls',
    'testicle',
    'testicles',
    'clitoris',
    'vulva',
    'rectum',

    // Scam / spam / malicious contact terms
    'phishing',
    'fraud',
    'fraudster',
    'scammer',
    'scammers',
    'hack',
    'hacker',
    'hacking',
    'fake',
    'click here',
    'free money',
    'double your money',
    'send money',
    'crypto scam',

    // Common harassment / degrading terms
    'idiot',
    'moron',
    'stupid',
    'retard',
    'loser',
    'freak',
    'pervert',
    'creep',
    'creepy',
    'pedophile',
    'pedophile',
    'molester',
    'rapist',

    // Common hateful / extremist terms
    'terrorist',
    'terrorism',
    'jihadist',
    'extremist',
    'kkk',
    'heil hitler',
    'hitler',
    'white supremacist',

    // Common religiously abusive profanity
    'allah hu akbar',
    'allah ka',
    'bhagwan ka',
    'bhagwan ki',
    'ram ka',
    'ram ki',
    'krishna ka',
    'krishna ki',
    'mandir tod',
    'masjid tod',
    'church tod',
    'muhammad ka',
    'jesus ka',
        '!',
        'ma',
        'chuda',
          '🖕',
    '🖕🏻',
    '🖕🏼',
    '🖕🏽',
    '🖕🏾',
    '🖕🏿',
    '🍆',
    '🍑',
    '💦',
    '👅',
    '🍌',
    '🔞',
    '@',
    '#',
    '$',
    '%',
    '^',
    '&',
    '*',
    '(',
    ')',
    '-',
    '_',
    '=',
    '+',
    '.',
    ',',
    '/',
    '\\',
    '|',
    ':',
    ';',
    '~',
    '`'

];

if (typeof window !== 'undefined') {
    window.omiglproBlockedWords = omiglproBlockedWords;
}

if (typeof module !== 'undefined' && module.exports) {
    module.exports = omiglproBlockedWords;
}